//
//  CountryStaticList.swift
//  AtlasMe
//
//  An extension on Country that provides a static list of all countries in the world,
//  complete with names, ISO codes, and geographic center coordinates.
//
//  The information in this list was provided by AI, verified with data from:
//  https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2
//

import Foundation

extension Country {
    static let allCountries: [Country] = [
        Country(name: "Afghanistan", alpha2: "AF", alpha3: "AFG", latitude: 33, longitude: 65),
        Country(name: "Albania", alpha2: "AL", alpha3: "ALB", latitude: 41, longitude: 20),
        Country(name: "Algeria", alpha2: "DZ", alpha3: "DZA", latitude: 28, longitude: 3),
        Country(name: "American Samoa", alpha2: "AS", alpha3: "ASM", latitude: -14.3333, longitude: -170),
        Country(name: "Andorra", alpha2: "AD", alpha3: "AND", latitude: 42.5, longitude: 1.6),
        Country(name: "Angola", alpha2: "AO", alpha3: "AGO", latitude: -12.5, longitude: 18.5),
        Country(name: "Anguilla", alpha2: "AI", alpha3: "AIA", latitude: 18.25, longitude: -63.1667),
        Country(name: "Antarctica", alpha2: "AQ", alpha3: "ATA", latitude: -90, longitude: 0),
        Country(name: "Antigua and Barbuda", alpha2: "AG", alpha3: "ATG", latitude: 17.05, longitude: -61.8),
        Country(name: "Argentina", alpha2: "AR", alpha3: "ARG", latitude: -34, longitude: -64),
        Country(name: "Armenia", alpha2: "AM", alpha3: "ARM", latitude: 40, longitude: 45),
        Country(name: "Aruba", alpha2: "AW", alpha3: "ABW", latitude: 12.5, longitude: -69.9667),
        Country(name: "Australia", alpha2: "AU", alpha3: "AUS", latitude: -27, longitude: 133),
        Country(name: "Austria", alpha2: "AT", alpha3: "AUT", latitude: 47.3333, longitude: 13.3333),
        Country(name: "Azerbaijan", alpha2: "AZ", alpha3: "AZE", latitude: 40.5, longitude: 47.5),
        Country(name: "Bahamas", alpha2: "BS", alpha3: "BHS", latitude: 24.25, longitude: -76),
        Country(name: "Bahrain", alpha2: "BH", alpha3: "BHR", latitude: 26, longitude: 50.55),
        Country(name: "Bangladesh", alpha2: "BD", alpha3: "BGD", latitude: 24, longitude: 90),
        Country(name: "Barbados", alpha2: "BB", alpha3: "BRB", latitude: 13.1667, longitude: -59.5333),
        Country(name: "Belarus", alpha2: "BY", alpha3: "BLR", latitude: 53, longitude: 28),
        Country(name: "Belgium", alpha2: "BE", alpha3: "BEL", latitude: 50.8333, longitude: 4),
        Country(name: "Belize", alpha2: "BZ", alpha3: "BLZ", latitude: 17.25, longitude: -88.75),
        Country(name: "Benin", alpha2: "BJ", alpha3: "BEN", latitude: 9.5, longitude: 2.25),
        Country(name: "Bermuda", alpha2: "BM", alpha3: "BMU", latitude: 32.3333, longitude: -64.75),
        Country(name: "Bhutan", alpha2: "BT", alpha3: "BTN", latitude: 27.5, longitude: 90.5),
        Country(name: "Bolivia, Plurinational State of", alpha2: "BO", alpha3: "BOL", latitude: -17, longitude: -65),
        Country(name: "Bosnia and Herzegovina", alpha2: "BA", alpha3: "BIH", latitude: 44, longitude: 18),
        Country(name: "Botswana", alpha2: "BW", alpha3: "BWA", latitude: -22, longitude: 24),
        Country(name: "Bouvet Island", alpha2: "BV", alpha3: "BVT", latitude: -54.4333, longitude: 3.4),
        Country(name: "Brazil", alpha2: "BR", alpha3: "BRA", latitude: -10, longitude: -55),
        Country(name: "British Indian Ocean Territory", alpha2: "IO", alpha3: "IOT", latitude: -6, longitude: 71.5),
        Country(name: "Brunei Darussalam", alpha2: "BN", alpha3: "BRN", latitude: 4.5, longitude: 114.6667),
        Country(name: "Bulgaria", alpha2: "BG", alpha3: "BGR", latitude: 43, longitude: 25),
        Country(name: "Burkina Faso", alpha2: "BF", alpha3: "BFA", latitude: 13, longitude: -2),
        Country(name: "Burundi", alpha2: "BI", alpha3: "BDI", latitude: -3.5, longitude: 30),
        Country(name: "Cambodia", alpha2: "KH", alpha3: "KHM", latitude: 13, longitude: 105),
        Country(name: "Cameroon", alpha2: "CM", alpha3: "CMR", latitude: 6, longitude: 12),
        Country(name: "Canada", alpha2: "CA", alpha3: "CAN", latitude: 60, longitude: -95),
        Country(name: "Cape Verde", alpha2: "CV", alpha3: "CPV", latitude: 16, longitude: -24),
        Country(name: "Cayman Islands", alpha2: "KY", alpha3: "CYM", latitude: 19.5, longitude: -80.5),
        Country(name: "Central African Republic", alpha2: "CF", alpha3: "CAF", latitude: 7, longitude: 21),
        Country(name: "Chad", alpha2: "TD", alpha3: "TCD", latitude: 15, longitude: 19),
        Country(name: "Chile", alpha2: "CL", alpha3: "CHL", latitude: -30, longitude: -71),
        Country(name: "China", alpha2: "CN", alpha3: "CHN", latitude: 35, longitude: 105),
        Country(name: "Christmas Island", alpha2: "CX", alpha3: "CXR", latitude: -10.5, longitude: 105.6667),
        Country(name: "Cocos (Keeling) Islands", alpha2: "CC", alpha3: "CCK", latitude: -12.5, longitude: 96.8333),
        Country(name: "Colombia", alpha2: "CO", alpha3: "COL", latitude: 4, longitude: -72),
        Country(name: "Comoros", alpha2: "KM", alpha3: "COM", latitude: -12.1667, longitude: 44.25),
        Country(name: "Congo", alpha2: "CG", alpha3: "COG", latitude: -1, longitude: 15),
        Country(name: "Congo, the Democratic Republic of the", alpha2: "CD", alpha3: "COD", latitude: 0, longitude: 25),
        Country(name: "Cook Islands", alpha2: "CK", alpha3: "COK", latitude: -21.2333, longitude: -159.7667),
        Country(name: "Costa Rica", alpha2: "CR", alpha3: "CRI", latitude: 10, longitude: -84),
        Country(name: "Côte d'Ivoire", alpha2: "CI", alpha3: "CIV", latitude: 8, longitude: -5),
        Country(name: "Croatia", alpha2: "HR", alpha3: "HRV", latitude: 45.1667, longitude: 15.5),
        Country(name: "Cuba", alpha2: "CU", alpha3: "CUB", latitude: 21.5, longitude: -80),
        Country(name: "Cyprus", alpha2: "CY", alpha3: "CYP", latitude: 35, longitude: 33),
        Country(name: "Czech Republic", alpha2: "CZ", alpha3: "CZE", latitude: 49.75, longitude: 15.5),
        Country(name: "Denmark", alpha2: "DK", alpha3: "DNK", latitude: 56, longitude: 10),
        Country(name: "Djibouti", alpha2: "DJ", alpha3: "DJI", latitude: 11.5, longitude: 43),
        Country(name: "Dominica", alpha2: "DM", alpha3: "DMA", latitude: 15.4167, longitude: -61.3333),
        Country(name: "Dominican Republic", alpha2: "DO", alpha3: "DOM", latitude: 19, longitude: -70.6667),
        Country(name: "Ecuador", alpha2: "EC", alpha3: "ECU", latitude: -2, longitude: -77.5),
        Country(name: "Egypt", alpha2: "EG", alpha3: "EGY", latitude: 27, longitude: 30),
        Country(name: "El Salvador", alpha2: "SV", alpha3: "SLV", latitude: 13.8333, longitude: -88.9167),
        Country(name: "Equatorial Guinea", alpha2: "GQ", alpha3: "GNQ", latitude: 2, longitude: 10),
        Country(name: "Eritrea", alpha2: "ER", alpha3: "ERI", latitude: 15, longitude: 39),
        Country(name: "Estonia", alpha2: "EE", alpha3: "EST", latitude: 59, longitude: 26),
        Country(name: "Ethiopia", alpha2: "ET", alpha3: "ETH", latitude: 8, longitude: 38),
        Country(name: "Falkland Islands (Malvinas)", alpha2: "FK", alpha3: "FLK", latitude: -51.75, longitude: -59),
        Country(name: "Faroe Islands", alpha2: "FO", alpha3: "FRO", latitude: 62, longitude: -7),
        Country(name: "Fiji", alpha2: "FJ", alpha3: "FJI", latitude: -18, longitude: 175),
        Country(name: "Finland", alpha2: "FI", alpha3: "FIN", latitude: 64, longitude: 26),
        Country(name: "France", alpha2: "FR", alpha3: "FRA", latitude: 46, longitude: 2),
        Country(name: "French Guiana", alpha2: "GF", alpha3: "GUF", latitude: 4, longitude: -53),
        Country(name: "French Polynesia", alpha2: "PF", alpha3: "PYF", latitude: -15, longitude: -140),
        Country(name: "French Southern Territories", alpha2: "TF", alpha3: "ATF", latitude: -43, longitude: 67),
        Country(name: "Gabon", alpha2: "GA", alpha3: "GAB", latitude: -1, longitude: 11.75),
        Country(name: "Gambia", alpha2: "GM", alpha3: "GMB", latitude: 13.4667, longitude: -16.5667),
        Country(name: "Georgia", alpha2: "GE", alpha3: "GEO", latitude: 42, longitude: 43.5),
        Country(name: "Germany", alpha2: "DE", alpha3: "DEU", latitude: 51, longitude: 9),
        Country(name: "Ghana", alpha2: "GH", alpha3: "GHA", latitude: 8, longitude: -2),
        Country(name: "Gibraltar", alpha2: "GI", alpha3: "GIB", latitude: 36.1833, longitude: -5.3667),
        Country(name: "Greece", alpha2: "GR", alpha3: "GRC", latitude: 39, longitude: 22),
        Country(name: "Greenland", alpha2: "GL", alpha3: "GRL", latitude: 72, longitude: -40),
        Country(name: "Grenada", alpha2: "GD", alpha3: "GRD", latitude: 12.1167, longitude: -61.6667),
        Country(name: "Guadeloupe", alpha2: "GP", alpha3: "GLP", latitude: 16.25, longitude: -61.5833),
        Country(name: "Guam", alpha2: "GU", alpha3: "GUM", latitude: 13.4667, longitude: 144.7833),
        Country(name: "Guatemala", alpha2: "GT", alpha3: "GTM", latitude: 15.5, longitude: -90.25),
        Country(name: "Guernsey", alpha2: "GG", alpha3: "GGY", latitude: 49.5, longitude: -2.56),
        Country(name: "Guinea", alpha2: "GN", alpha3: "GIN", latitude: 11, longitude: -10),
        Country(name: "Guinea-Bissau", alpha2: "GW", alpha3: "GNB", latitude: 12, longitude: -15),
        Country(name: "Guyana", alpha2: "GY", alpha3: "GUY", latitude: 5, longitude: -59),
        Country(name: "Haiti", alpha2: "HT", alpha3: "HTI", latitude: 19, longitude: -72.4167),
        Country(name: "Heard Island and McDonald Islands", alpha2: "HM", alpha3: "HMD",
                latitude: -53.1, longitude: 72.5167),
        Country(name: "Holy See (Vatican City State)", alpha2: "VA", alpha3: "VAT", latitude: 41.9, longitude: 12.45),
        Country(name: "Honduras", alpha2: "HN", alpha3: "HND", latitude: 15, longitude: -86.5),
        Country(name: "Hong Kong", alpha2: "HK", alpha3: "HKG", latitude: 22.25, longitude: 114.1667),
        Country(name: "Hungary", alpha2: "HU", alpha3: "HUN", latitude: 47, longitude: 20),
        Country(name: "Iceland", alpha2: "IS", alpha3: "ISL", latitude: 65, longitude: -18),
        Country(name: "India", alpha2: "IN", alpha3: "IND", latitude: 20, longitude: 77),
        Country(name: "Indonesia", alpha2: "ID", alpha3: "IDN", latitude: -5, longitude: 120),
        Country(name: "Iran, Islamic Republic of", alpha2: "IR", alpha3: "IRN", latitude: 32, longitude: 53),
        Country(name: "Iraq", alpha2: "IQ", alpha3: "IRQ", latitude: 33, longitude: 44),
        Country(name: "Ireland", alpha2: "IE", alpha3: "IRL", latitude: 53, longitude: -8),
        Country(name: "Isle of Man", alpha2: "IM", alpha3: "IMN", latitude: 54.23, longitude: -4.55),
        Country(name: "Israel", alpha2: "IL", alpha3: "ISR", latitude: 31.5, longitude: 34.75),
        Country(name: "Italy", alpha2: "IT", alpha3: "ITA", latitude: 42.8333, longitude: 12.8333),
        Country(name: "Jamaica", alpha2: "JM", alpha3: "JAM", latitude: 18.25, longitude: -77.5),
        Country(name: "Japan", alpha2: "JP", alpha3: "JPN", latitude: 36, longitude: 138),
        Country(name: "Jersey", alpha2: "JE", alpha3: "JEY", latitude: 49.21, longitude: -2.13),
        Country(name: "Jordan", alpha2: "JO", alpha3: "JOR", latitude: 31, longitude: 36),
        Country(name: "Kazakhstan", alpha2: "KZ", alpha3: "KAZ", latitude: 48, longitude: 68),
        Country(name: "Kenya", alpha2: "KE", alpha3: "KEN", latitude: 1, longitude: 38),
        Country(name: "Kiribati", alpha2: "KI", alpha3: "KIR", latitude: 1.4167, longitude: 173),
        Country(name: "Korea, Democratic People's Republic of", alpha2: "KP", alpha3: "PRK",
                latitude: 40, longitude: 127),
        Country(name: "Korea, Republic of", alpha2: "KR", alpha3: "KOR", latitude: 37, longitude: 127.5),
        Country(name: "Kuwait", alpha2: "KW", alpha3: "KWT", latitude: 29.3375, longitude: 47.6581),
        Country(name: "Kyrgyzstan", alpha2: "KG", alpha3: "KGZ", latitude: 41, longitude: 75),
        Country(name: "Lao People's Democratic Republic", alpha2: "LA", alpha3: "LAO",
                latitude: 18, longitude: 105),
        Country(name: "Latvia", alpha2: "LV", alpha3: "LVA", latitude: 57, longitude: 25),
        Country(name: "Lebanon", alpha2: "LB", alpha3: "LBN", latitude: 33.8333, longitude: 35.8333),
        Country(name: "Lesotho", alpha2: "LS", alpha3: "LSO", latitude: -29.5, longitude: 28.5),
        Country(name: "Liberia", alpha2: "LR", alpha3: "LBR", latitude: 6.5, longitude: -9.5),
        Country(name: "Libyan Arab Jamahiriya", alpha2: "LY", alpha3: "LBY", latitude: 25, longitude: 17),
        Country(name: "Liechtenstein", alpha2: "LI", alpha3: "LIE", latitude: 47.1667, longitude: 9.5333),
        Country(name: "Lithuania", alpha2: "LT", alpha3: "LTU", latitude: 56, longitude: 24),
        Country(name: "Luxembourg", alpha2: "LU", alpha3: "LUX", latitude: 49.75, longitude: 6.1667),
        Country(name: "Macao", alpha2: "MO", alpha3: "MAC", latitude: 22.1667, longitude: 113.55),
        Country(name: "Macedonia, the former Yugoslav Republic of", alpha2: "MK", alpha3: "MKD",
                latitude: 41.8333, longitude: 22),
        Country(name: "Madagascar", alpha2: "MG", alpha3: "MDG", latitude: -20, longitude: 47),
        Country(name: "Malawi", alpha2: "MW", alpha3: "MWI", latitude: -13.5, longitude: 34),
        Country(name: "Malaysia", alpha2: "MY", alpha3: "MYS", latitude: 2.5, longitude: 112.5),
        Country(name: "Maldives", alpha2: "MV", alpha3: "MDV", latitude: 3.25, longitude: 73),
        Country(name: "Mali", alpha2: "ML", alpha3: "MLI", latitude: 17, longitude: -4),
        Country(name: "Malta", alpha2: "MT", alpha3: "MLT", latitude: 35.8333, longitude: 14.5833),
        Country(name: "Marshall Islands", alpha2: "MH", alpha3: "MHL", latitude: 9, longitude: 168),
        Country(name: "Martinique", alpha2: "MQ", alpha3: "MTQ", latitude: 14.6667, longitude: -61),
        Country(name: "Mauritania", alpha2: "MR", alpha3: "MRT", latitude: 20, longitude: -12),
        Country(name: "Mauritius", alpha2: "MU", alpha3: "MUS", latitude: -20.2833, longitude: 57.55),
        Country(name: "Mayotte", alpha2: "YT", alpha3: "MYT", latitude: -12.8333, longitude: 45.1667),
        Country(name: "Mexico", alpha2: "MX", alpha3: "MEX", latitude: 23, longitude: -102),
        Country(name: "Micronesia, Federated States of", alpha2: "FM", alpha3: "FSM",
                latitude: 6.9167, longitude: 158.25),
        Country(name: "Moldova, Republic of", alpha2: "MD", alpha3: "MDA", latitude: 47, longitude: 29),
        Country(name: "Monaco", alpha2: "MC", alpha3: "MCO", latitude: 43.7333, longitude: 7.4),
        Country(name: "Mongolia", alpha2: "MN", alpha3: "MNG", latitude: 46, longitude: 105),
        Country(name: "Montenegro", alpha2: "ME", alpha3: "MNE", latitude: 42, longitude: 19),
        Country(name: "Montserrat", alpha2: "MS", alpha3: "MSR", latitude: 16.75, longitude: -62.2),
        Country(name: "Morocco", alpha2: "MA", alpha3: "MAR", latitude: 32, longitude: -5),
        Country(name: "Mozambique", alpha2: "MZ", alpha3: "MOZ", latitude: -18.25, longitude: 35),
        Country(name: "Myanmar", alpha2: "MM", alpha3: "MMR", latitude: 22, longitude: 98),
        Country(name: "Namibia", alpha2: "NA", alpha3: "NAM", latitude: -22, longitude: 17),
        Country(name: "Nauru", alpha2: "NR", alpha3: "NRU", latitude: -0.5333, longitude: 166.9167),
        Country(name: "Nepal", alpha2: "NP", alpha3: "NPL", latitude: 28, longitude: 84),
        Country(name: "Netherlands", alpha2: "NL", alpha3: "NLD", latitude: 52.5, longitude: 5.75),
        Country(name: "Netherlands Antilles", alpha2: "AN", alpha3: "ANT", latitude: 12.25, longitude: -68.75),
        Country(name: "New Caledonia", alpha2: "NC", alpha3: "NCL", latitude: -21.5, longitude: 165.5),
        Country(name: "New Zealand", alpha2: "NZ", alpha3: "NZL", latitude: -41, longitude: 174),
        Country(name: "Nicaragua", alpha2: "NI", alpha3: "NIC", latitude: 13, longitude: -85),
        Country(name: "Niger", alpha2: "NE", alpha3: "NER", latitude: 16, longitude: 8),
        Country(name: "Nigeria", alpha2: "NG", alpha3: "NGA", latitude: 10, longitude: 8),
        Country(name: "Niue", alpha2: "NU", alpha3: "NIU", latitude: -19.0333, longitude: -169.8667),
        Country(name: "Norfolk Island", alpha2: "NF", alpha3: "NFK", latitude: -29.0333, longitude: 167.95),
        Country(name: "Northern Mariana Islands", alpha2: "MP", alpha3: "MNP", latitude: 15.2, longitude: 145.75),
        Country(name: "Norway", alpha2: "NO", alpha3: "NOR", latitude: 62, longitude: 10),
        Country(name: "Oman", alpha2: "OM", alpha3: "OMN", latitude: 21, longitude: 57),
        Country(name: "Pakistan", alpha2: "PK", alpha3: "PAK", latitude: 30, longitude: 70),
        Country(name: "Palau", alpha2: "PW", alpha3: "PLW", latitude: 7.5, longitude: 134.5),
        Country(name: "Palestinian Territory, Occupied", alpha2: "PS", alpha3: "PSE",
                latitude: 32, longitude: 35.25),
        Country(name: "Panama", alpha2: "PA", alpha3: "PAN", latitude: 9, longitude: -80),
        Country(name: "Papua New Guinea", alpha2: "PG", alpha3: "PNG", latitude: -6, longitude: 147),
        Country(name: "Paraguay", alpha2: "PY", alpha3: "PRY", latitude: -23, longitude: -58),
        Country(name: "Peru", alpha2: "PE", alpha3: "PER", latitude: -10, longitude: -76),
        Country(name: "Philippines", alpha2: "PH", alpha3: "PHL", latitude: 13, longitude: 122),
        Country(name: "Pitcairn", alpha2: "PN", alpha3: "PCN", latitude: -24.7, longitude: -127.4),
        Country(name: "Poland", alpha2: "PL", alpha3: "POL", latitude: 52, longitude: 20),
        Country(name: "Portugal", alpha2: "PT", alpha3: "PRT", latitude: 39.5, longitude: -8),
        Country(name: "Puerto Rico", alpha2: "PR", alpha3: "PRI", latitude: 18.25, longitude: -66.5),
        Country(name: "Qatar", alpha2: "QA", alpha3: "QAT", latitude: 25.5, longitude: 51.25),
        Country(name: "Réunion", alpha2: "RE", alpha3: "REU", latitude: -21.1, longitude: 55.6),
        Country(name: "Romania", alpha2: "RO", alpha3: "ROU", latitude: 46, longitude: 25),
        Country(name: "Russian Federation", alpha2: "RU", alpha3: "RUS", latitude: 60, longitude: 100),
        Country(name: "Rwanda", alpha2: "RW", alpha3: "RWA", latitude: -2, longitude: 30),
        Country(name: "Saint Helena, Ascension and Tristan da Cunha", alpha2: "SH", alpha3: "SHN",
                latitude: -15.9333, longitude: -5.7),
        Country(name: "Saint Kitts and Nevis", alpha2: "KN", alpha3: "KNA", latitude: 17.3333, longitude: -62.75),
        Country(name: "Saint Lucia", alpha2: "LC", alpha3: "LCA", latitude: 13.8833, longitude: -61.1333),
        Country(name: "Saint Pierre and Miquelon", alpha2: "PM", alpha3: "SPM",
                latitude: 46.8333, longitude: -56.3333),
        Country(name: "Saint Vincent and the Grenadines", alpha2: "VC", alpha3: "VCT",
                latitude: 13.25, longitude: -61.2),
        Country(name: "Samoa", alpha2: "WS", alpha3: "WSM", latitude: -13.5833, longitude: -172.3333),
        Country(name: "San Marino", alpha2: "SM", alpha3: "SMR", latitude: 43.7667, longitude: 12.4167),
        Country(name: "Sao Tome and Principe", alpha2: "ST", alpha3: "STP", latitude: 1, longitude: 7),
        Country(name: "Saudi Arabia", alpha2: "SA", alpha3: "SAU", latitude: 25, longitude: 45),
        Country(name: "Senegal", alpha2: "SN", alpha3: "SEN", latitude: 14, longitude: -14),
        Country(name: "Serbia", alpha2: "RS", alpha3: "SRB", latitude: 44, longitude: 21),
        Country(name: "Seychelles", alpha2: "SC", alpha3: "SYC", latitude: -4.5833, longitude: 55.6667),
        Country(name: "Sierra Leone", alpha2: "SL", alpha3: "SLE", latitude: 8.5, longitude: -11.5),
        Country(name: "Singapore", alpha2: "SG", alpha3: "SGP", latitude: 1.3667, longitude: 103.8),
        Country(name: "Slovakia", alpha2: "SK", alpha3: "SVK", latitude: 48.6667, longitude: 19.5),
        Country(name: "Slovenia", alpha2: "SI", alpha3: "SVN", latitude: 46, longitude: 15),
        Country(name: "Solomon Islands", alpha2: "SB", alpha3: "SLB", latitude: -8, longitude: 159),
        Country(name: "Somalia", alpha2: "SO", alpha3: "SOM", latitude: 10, longitude: 49),
        Country(name: "South Africa", alpha2: "ZA", alpha3: "ZAF", latitude: -29, longitude: 24),
        Country(name: "South Georgia and the South Sandwich Islands", alpha2: "GS", alpha3: "SGS",
                latitude: -54.5, longitude: -37),
        Country(name: "Spain", alpha2: "ES", alpha3: "ESP", latitude: 40, longitude: -4),
        Country(name: "Sri Lanka", alpha2: "LK", alpha3: "LKA", latitude: 7, longitude: 81),
        Country(name: "Sudan", alpha2: "SD", alpha3: "SDN", latitude: 15, longitude: 30),
        Country(name: "Suriname", alpha2: "SR", alpha3: "SUR", latitude: 4, longitude: -56),
        Country(name: "Svalbard and Jan Mayen", alpha2: "SJ", alpha3: "SJM", latitude: 78, longitude: 20),
        Country(name: "Swaziland", alpha2: "SZ", alpha3: "SWZ", latitude: -26.5, longitude: 31.5),
        Country(name: "Sweden", alpha2: "SE", alpha3: "SWE", latitude: 62, longitude: 15),
        Country(name: "Switzerland", alpha2: "CH", alpha3: "CHE", latitude: 47, longitude: 8),
        Country(name: "Syrian Arab Republic", alpha2: "SY", alpha3: "SYR", latitude: 35, longitude: 38),
        Country(name: "Taiwan, Province of China", alpha2: "TW", alpha3: "TWN", latitude: 23.5, longitude: 121),
        Country(name: "Tajikistan", alpha2: "TJ", alpha3: "TJK", latitude: 39, longitude: 71),
        Country(name: "Tanzania, United Republic of", alpha2: "TZ", alpha3: "TZA", latitude: -6, longitude: 35),
        Country(name: "Thailand", alpha2: "TH", alpha3: "THA", latitude: 15, longitude: 100),
        Country(name: "Timor-Leste", alpha2: "TL", alpha3: "TLS", latitude: -8.55, longitude: 125.5167),
        Country(name: "Togo", alpha2: "TG", alpha3: "TGO", latitude: 8, longitude: 1.1667),
        Country(name: "Tokelau", alpha2: "TK", alpha3: "TKL", latitude: -9, longitude: -172),
        Country(name: "Tonga", alpha2: "TO", alpha3: "TON", latitude: -20, longitude: -175),
        Country(name: "Trinidad and Tobago", alpha2: "TT", alpha3: "TTO", latitude: 11, longitude: -61),
        Country(name: "Tunisia", alpha2: "TN", alpha3: "TUN", latitude: 34, longitude: 9),
        Country(name: "Turkey", alpha2: "TR", alpha3: "TUR", latitude: 39, longitude: 35),
        Country(name: "Turkmenistan", alpha2: "TM", alpha3: "TKM", latitude: 40, longitude: 60),
        Country(name: "Turks and Caicos Islands", alpha2: "TC", alpha3: "TCA", latitude: 21.75, longitude: -71.5833),
        Country(name: "Tuvalu", alpha2: "TV", alpha3: "TUV", latitude: -8, longitude: 178),
        Country(name: "Uganda", alpha2: "UG", alpha3: "UGA", latitude: 1, longitude: 32),
        Country(name: "Ukraine", alpha2: "UA", alpha3: "UKR", latitude: 49, longitude: 32),
        Country(name: "United Arab Emirates", alpha2: "AE", alpha3: "ARE", latitude: 24, longitude: 54),
        Country(name: "United Kingdom", alpha2: "GB", alpha3: "GBR", latitude: 54, longitude: -2),
        Country(name: "United States", alpha2: "US", alpha3: "USA", latitude: 38, longitude: -97),
        Country(name: "United States Minor Outlying Islands", alpha2: "UM", alpha3: "UMI",
                latitude: 19.2833, longitude: 166.6),
        Country(name: "Uruguay", alpha2: "UY", alpha3: "URY", latitude: -33, longitude: -56),
        Country(name: "Uzbekistan", alpha2: "UZ", alpha3: "UZB", latitude: 41, longitude: 64),
        Country(name: "Vanuatu", alpha2: "VU", alpha3: "VUT", latitude: -16, longitude: 167),
        Country(name: "Venezuela, Bolivarian Republic of", alpha2: "VE", alpha3: "VEN", latitude: 8, longitude: -66),
        Country(name: "Viet Nam", alpha2: "VN", alpha3: "VNM", latitude: 16, longitude: 106),
        Country(name: "Virgin Islands, British", alpha2: "VG", alpha3: "VGB",
                latitude: 18.5, longitude: -64.5),
        Country(name: "Virgin Islands, U.S.", alpha2: "VI", alpha3: "VIR",
                latitude: 18.3333, longitude: -64.8333),
        Country(name: "Wallis and Futuna", alpha2: "WF", alpha3: "WLF", latitude: -13.3, longitude: -176.2),
        Country(name: "Western Sahara", alpha2: "EH", alpha3: "ESH", latitude: 24.5, longitude: -13),
        Country(name: "Yemen", alpha2: "YE", alpha3: "YEM", latitude: 15, longitude: 48),
        Country(name: "Zambia", alpha2: "ZM", alpha3: "ZMB", latitude: -15, longitude: 30),
        Country(name: "Zimbabwe", alpha2: "ZW", alpha3: "ZWE", latitude: -20, longitude: 30)
    ]
}
